name: video_streaming_flutter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  video_player: ^1.0.1
  chewie: ^0.12.1+1
  shimmer: ^1.1.2
  carousel_slider: ^1.3.0
  cached_network_image: ^2.1.0+1
  animations: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Bold.ttf
        - asset: assets/font/Poppins-SemiBold.ttf
